# Generated by Django 4.1.3 on 2022-11-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="r1",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="images",
            name="r2",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="images",
            name="s1",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="images",
            name="s2",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="images",
            name="gamma",
            field=models.IntegerField(default=0),
        ),
    ]
