# Generated by Django 4.1 on 2022-11-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0003_alter_images_filters_alter_images_gamma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="filters",
            field=models.CharField(
                choices=[
                    ("gamma", "gamma"),
                    ("log", "log"),
                    ("histogram", "histogram"),
                    ("contrast", "contrast"),
                    ("median", "median"),
                    ("mode", "mode"),
                    ("mean", "mean"),
                    ("Laplacian", "Laplacian"),
                ],
                default="gamma",
                max_length=23,
            ),
        ),
    ]
